// ==========================================================================
// Dados de demonstração (100% fictícios)
// --------------------------------------------------------------------------
// Usados apenas no primeiro acesso / quando o backend (/api/sync) está
// indisponível. Substitua livremente pelos seus próprios lançamentos ou
// restaure tudo pelo botão "Restaurar dados de exemplo".
// ==========================================================================
window.DADOS_INICIAIS = {
  controle_financeiro: [
    {
      TIPO: "MERCADO",
      VALOR: 254.9,
      DISCRIMINACAO: "Supermercado Exemplo",
      DATA: "05/08/2026",
      VENCIMENTO: "AGOSTO",
      ANO: 2026,
      ENTRADA_SAIDA: "DESPESA",
      OBSERVACAO: "GASTOS VARIÁVEIS",
    },
    {
      TIPO: "SALÁRIO",
      VALOR: 4500.0,
      DISCRIMINACAO: "Salário mensal",
      DATA: "05/08/2026",
      VENCIMENTO: "AGOSTO",
      ANO: 2026,
      ENTRADA_SAIDA: "RECEITA",
      OBSERVACAO: "RECEITA",
    },
    {
      TIPO: "GASOLINA CAR",
      VALOR: 180.0,
      DISCRIMINACAO: "Posto de combustível Exemplo",
      DATA: "12/08/2026",
      VENCIMENTO: "AGOSTO",
      ANO: 2026,
      ENTRADA_SAIDA: "DESPESA",
      OBSERVACAO: "GASTOS VARIÁVEIS",
    },
  ],

  controle_dividas: [
    {
      TIPO: "CARTÃO EXEMPLO",
      DISCRIMINACAO: "Fone de ouvido",
      VALOR: 133.33,
      PARCELAS: 1,
      QTD_PARCELAS: 3,
      DATA: "15/07/2026",
      VENCIMENTO: "AGOSTO",
      ANO: "2026",
      CONDICAO: "PAGO",
      OBSERVACAO: "PARCELADOS",
    },
    {
      TIPO: "INTERNET",
      DISCRIMINACAO: "Internet fibra",
      VALOR: 99.9,
      PARCELAS: 1,
      QTD_PARCELAS: 1,
      DATA: "10/08/2026",
      VENCIMENTO: "SETEMBRO",
      ANO: "2026",
      CONDICAO: "À PAGAR",
      OBSERVACAO: "GASTOS FIXOS",
    },
    {
      TIPO: "VENDA",
      DISCRIMINACAO: "Venda de bicicleta usada",
      VALOR: 400.0,
      PARCELAS: 2,
      QTD_PARCELAS: 2,
      DATA: "20/08/2026",
      VENCIMENTO: "SETEMBRO",
      ANO: "2026",
      CONDICAO: "RECEBIDO",
      OBSERVACAO: "RECEBIDO",
    },
  ],

  cadastros: {
    gastos_variaveis: [
      "MERCADO",
      "DESPENSA",
      "GASOLINA CAR",
      "GASOLINA MOT",
      "LAZER",
      "MANUTENÇÃO",
      "PET",
      "FARMÁCIA",
      "DIVERSOS",
      "GÁS COZINHA",
    ],
    fixos_parcelados: [
      "CARTÃO EXEMPLO",
      "CDC EXEMPLO",
      "EMPRÉSTIMO",
      " ENERGIA",
      " ÁGUA",
      " INTERNET",
      "COTA EXEMPLO",
      "STREAMING",
      "ACADEMIA",
      "BEMOL",
      "VENDA",
      "PAGAR",
    ],
    receitas: ["SALÁRIO", "EXTRAS", "OUTRAS RECEITAS"],
    receitas_variaveis: [
      "SALÁRIO",
      "EXTRAS",
      "MERCADO",
      "DESPENSA",
      "GASOLINA CAR",
      "GASOLINA MOT",
      "LAZER",
      "MANUTENÇÃO",
      "PET",
      "FARMÁCIA",
      "DIVERSOS",
      "GÁS COZINHA",
    ],
    cartoes_credito: ["CARTÃO EXEMPLO", "CDC EXEMPLO"],
  },

  resumo_meta: {
    ano_atual: 2026,
    mes_atual: "AGOSTO",
    orcamento: [
      { categoria: "MERCADO", orcamento: 800.0 },
      { categoria: "DESPENSA", orcamento: 650.0 },
      { categoria: "PET", orcamento: 120.0 },
      { categoria: "FARMÁCIA", orcamento: 100.0 },
      { categoria: "GASOLINA CAR", orcamento: 450.0 },
      { categoria: "GASOLINA MOT", orcamento: 20.0 },
      { categoria: "LAZER", orcamento: 0.0 },
      { categoria: "MANUTENÇÃO", orcamento: 0.0 },
      { categoria: "DIVERSOS", orcamento: 0.0 },
      { categoria: "GÁS COZINHA", orcamento: 105.0 },
    ],
  },
};
